client/.eslintrc.json, client/package-lock.json, client/package.json, client/src/Components/App.js, client/src/Components/Layouts/Home.js
Fixes #50 
description:
initiate eslint inside the client folder.
code refactoring depending on eslint warnings.
=> Fix eslint

server/database/surveyBuild.js
=> Fix promises in Survey build

__test__/edit_session.js, client/__mocks__/axios.js, client/package-lock.json, client/package.json, client/src/Components/App.js, client/src/Components/Layouts/EditSession/__snapshots__/edit_session.test.js.snap, client/src/Components/Layouts/EditSession/edit_session.test.js, client/src/Components/Layouts/EditSession/index.js, client/src/Components/Layouts/EditSession/options.js, client/src/Components/Layouts/EditSession/styledComponents.js, client/src/Components/Layouts/Session-Details/Action.js, client/src/Components/Layouts/Session-Details/Actions.js, client/src/Components/Layouts/Session-Details/Content.js, client/src/Components/Layouts/Session-Details/Link.js, client/src/Components/Layouts/Session-Details/ResultBtn.js, client/src/Components/Layouts/Session-Details/__snapshots__/Session.test.js.snap, client/src/Components/Layouts/Session-Details/styledComponents.js, client/src/Components/Layouts/view-sessions/__snapshots__/viewSessions.test.js.snap, client/src/Components/Layouts/view-sessions/index.js, client/src/Components/Layouts/view-sessions/styledComponents.js, package-lock.json, server/controllers/edit_session.js, server/controllers/index.js, server/database/queries/edit_session.js
=> Edit session

client/package-lock.json, client/src/Components/Layouts/Session-Details/__snapshots__/Session.test.js.snap, package-lock.json
Relates #95 
Fix security alerts for vulnerable dependencies that found in the project.
=> fix security alerts for vulnerable dependencies

client/src/Components/Layouts/CreateSession/FormElements.js, client/src/Components/Layouts/CreateSession/__snapshots__/CreateSession.test.js.snap, client/src/Components/Layouts/CreateSession/index.js, client/src/Components/Layouts/EditSession/__snapshots__/edit_session.test.js.snap, client/src/Components/Layouts/EditSession/index.js, client/src/Components/Layouts/EditSession/styledComponents.js, client/src/Components/Layouts/TrainersLandingPage/__snapshots__/TrainersLandingPage.test.js.snap, client/src/Components/Layouts/TrainersLandingPage/index.js
Fixed small error relating to edit session #130
=> Minor fixes

v2/server/database/data/development/responses.js, v2/server/database/data/test/responses.js
fix the null values in the responses
=> fix: null values in some responses

v2/client/src/components/App.js, v2/client/src/components/common/List/List.style.js, v2/client/src/components/common/List/SessionList.js, v2/client/src/components/common/List/TrainerList.js, v2/client/src/components/common/Toggle/index.js, v2/client/src/components/pages/LandingPage/index.js
Added trainerlist and session list common components now as well > related to #183
=> Style setup

v2/client/src/components/App.js, v2/client/src/components/common/Button/index.js, v2/client/src/components/common/List/List.style.js, v2/client/src/components/common/List/TrainerList.js, v2/client/src/components/common/modal/index.js, v2/client/src/components/pages/TrainerListPage/TrainerListPage.style.js, v2/client/src/components/pages/TrainerListPage/index.js, v2/client/src/constants/navigationRoutes.js, v2/client/src/helpers/stringCutter.js, v2/client/src/theme.js, v2/server/__test__/api/users.getAllTrainersAndLeads.js, v2/server/__test__/api/users.getListofTrainers.js, v2/server/__test__/database/queries/getAllLocalLeads.js, v2/server/__test__/database/queries/getAllTrainers.js, v2/server/__test__/database/queries/getMyTrainers.js, v2/server/controllers/users/user.js, v2/server/database/queries/users/admin.js, v2/server/database/queries/users/loaclLead.js, v2/server/router/users.js
Relates to:
#174 
#216 
#218 
#217 
#219 
#175
=> Trainer & Local Lead Lists

v2/client/src/actions/users.js, v2/client/src/components/common/Feedback/index.js, v2/client/src/components/pages/TrainerFeedback/index.js, v2/server/controllers/feedback/getTrainerFeedback.js, v2/server/database/data/development/answers.js, v2/server/database/data/development/responses.js, v2/server/database/data/development/sessions.js, v2/server/database/queries/feedback/trainer.js
relates #251 
- takes sessionId and surveyType as req.body => to test go to TrainerFeedback and give those two consts values from your db (best is to use trainer alex with train the trainer session and then u can decide what survey type (pre/post..)
- url  http://localhost:3000/trainer-results/feedback/:trainerId
=> Trainer feedback

v2/client/src/components/pages/survey/Questions.js, v2/client/src/components/pages/survey/Questions.style.js, v2/client/src/components/pages/survey/Survey.js, v2/client/src/theme.js, v2/server/__test__/database/queries/getMyTrainers.js, v2/server/controllers/survey/storeSurvey.js, v2/server/database/models/Response.js, v2/server/database/queries/surveys/storeResponse.js
relates #258 and updates form styling
/survey/:survey-type&:sessionId
=> Survey update

v2/client/src/components/common/List/List.style.js, v2/client/src/components/common/List/TrainerList.js, v2/client/src/components/pages/TrainerListPage/index.js, v2/server/controllers/users/removeTrainerToGroup.js, v2/server/database/queries/users/localLead/index.js, v2/server/router/users.js
=> local lead can delete a trainer from his group

v2/client/src/components/pages/survey/Questions.js, v2/client/src/components/pages/survey/Questions.style.js, v2/client/src/components/pages/survey/Survey.js, v2/client/src/components/pages/survey/Survey.style.js, v2/server/database/DBConstants.js, v2/server/database/data/development/questions.js, v2/server/database/models/Question.js, v2/server/database/queries/surveys/surveyQuestions.js
Further tweaks to the survey:
- Changed data, backend query and front end logic so it now  renders the questions in the correct order
- Styled the questions and inputs further
- Added a progress tracker
NOTE: REBUILD DATABASE FIRST
=> Style survey

v2/client/src/actions/groupSessionsAction.js, v2/server/controllers/users/getLocalLeadSessions.js
Fixed a 404 time out bug on sessions
=> 404 session fix

v2/client/src/components/pages/SessionDetails/SessionSurveys/SurveyContent.js, v2/client/src/components/pages/survey/Survey.js
=> Fix survey link and participant login bugs

v2/client/src/components/App.js, v2/client/src/components/pages/survey/Questions.js, v2/client/src/components/pages/survey/Questions.style.js, v2/client/src/components/pages/survey/Survey.js
=> change start of weekday in datepickers to Monday

package-lock.json, package.json, v2/client/src/components/pages/SessionDetails/SessionSurveys/index.js, v2/server/__test__/api/getSurveyQs.js, v2/server/__test__/database/queries/surveyQueries.js, v2/server/database/data/development/sessions.js, v2/server/database/data/test/sessions.js, v2/server/database/models/Session.js, v2/server/database/queries/add_session.js, v2/server/database/queries/surveys/surveyQuestions.js
=> Short survey URL

v2/client/src/components/App.js, v2/client/src/components/pages/Certificate/index.js, v2/client/src/components/pages/Login/LoginParticipant.js, v2/client/src/components/pages/ParticipantProgress/SessionsList.js, v2/client/src/components/pages/ParticipantProgress/index.js, v2/client/src/components/pages/survey/Survey.js, v2/client/src/components/pages/userDashboard.js, v2/client/src/constants/surveyTypes.js, v2/client/src/helpers/index.js, v2/server/controllers/users/getParticipantSessions.js, v2/server/database/queries/users/participantSessionQuery.js
=> Congrats message

v2/client/src/components/pages/CreateSession/create-session.style.js, v2/client/src/components/pages/CreateSession/index.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/components/pages/SessionDetails/SessionSurveys/index.js, v2/client/src/components/pages/userDashboard.js
Relates to #350 #348 
Also added log out button to participant dashboard
=> Fix copy bug > #350

v2/client/src/actions/sessionAction.js, v2/client/src/components/pages/CreateSession/create-session.style.js, v2/client/src/components/pages/CreateSession/index.js, v2/client/src/components/pages/SessionDetails/InviteAndPromote/SendInvitation.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/reducers/sessionReducer.js, v2/server/controllers/addSession.js, v2/server/controllers/users/sendInvitation.js, v2/server/database/queries/addSession.js, v2/server/database/queries/users/sendInvitation.js, v2/server/helpers/emails/sendEmailInvitation.js
=> Checkbox copy

v2/client/src/components/common/Header/index.js, v2/client/src/components/pages/Certificate/ClaimCertificate.js, v2/client/src/components/pages/Certificate/NameForm.js, v2/client/src/components/pages/Certificate/SucessMsg.js, v2/client/src/components/pages/Certificate/index.js, v2/client/src/components/pages/ParticipantBehavioral/index.js, v2/client/src/components/pages/ParticipantProgress/index.js, v2/client/src/components/pages/SessionsFiles/index.js, v2/client/src/components/pages/userDashboard.js
=> Add header with home icon to particepent views

v2/client/src/components/pages/SessionDetails/ManageAttendees/ViewEmailsList.js, v2/client/src/components/pages/SessionDetails/ManageAttendees/index.js, v2/client/src/components/pages/SessionDetails/SessionDetails.Style.js, v2/client/src/components/pages/userDashboard.js, v2/server/app.js, v2/server/taskScheduler/sendScheduledEmails.js
=> Schedule emails

v2/client/src/actions/authAction.js, v2/client/src/actions/groupSessionsAction.js, v2/client/src/actions/sessionAction.js, v2/client/src/components/App.js, v2/client/src/components/common/Navbar/index.js, v2/client/src/components/pages/ConfirmRegistration/index.js, v2/client/src/components/pages/CreateSession/index.js, v2/client/src/components/pages/LandingPage/index.js, v2/client/src/components/pages/SessionDetails/InviteAndPromote/SendInvitation.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/components/pages/SessionDetails/SessionSurveys/index.js, v2/client/src/constants/userTypes.js, v2/client/src/reducers/authReducer.js, v2/client/src/reducers/index.js, v2/server/controllers/addSession.js, v2/server/controllers/survey/emailSurvey.js, v2/server/controllers/users/sendInvitation.js, v2/server/database/queries/users/sendInvitation.js
1. Clear all the store data on logout
2. Redirect the logged-in user to the right dashboard
=> Fix auth bugs

v2/server/helpers/emails/index.js, v2/server/helpers/emails/sendEmailInvitation.js, v2/server/helpers/emails/sendSessionReminder.js, v2/server/helpers/emails/sendSurvey.js
=> change the recipient bcc

v2/client/src/components/pages/survey/ConfirmSurvey.js, v2/client/src/components/pages/survey/EnterPIN.js, v2/client/src/components/pages/survey/Survey.style.js
=> Add important note + change `date` to `day`

v2/client/src/components/pages/LandingPage/index.js, v2/client/src/components/pages/SessionsFiles/index.js
show materials for users they've filled out the pre-survey #393
add a link to the user manual into the landing page #392
=> show materials, and user manual

v2/client/src/components/pages/SessionDetails/InviteAndPromote/InviteeList.js, v2/client/src/components/pages/SessionDetails/InviteAndPromote/SendInvitation.js, v2/server/controllers/users/sendInvitation.js, v2/server/controllers/users/updatSendInvitation.js, v2/server/database/models/Session.js, v2/server/helpers/emails/sendEmailInvitation.js
=> Fix email bugs

v2/client/package-lock.json, v2/client/src/actions/sessionAction.js, v2/client/src/components/common/Button/index.js, v2/client/src/components/common/Feedback/Feedback.style.js, v2/client/src/components/common/List/EmailsList.js, v2/client/src/components/common/List/List.style.js, v2/client/src/components/common/List/SessionList.js, v2/client/src/components/common/Menu/index.js, v2/client/src/components/common/Navbar/index.js, v2/client/src/components/common/Reach/index.js, v2/client/src/components/pages/CreateSession/create-session.style.js, v2/client/src/components/pages/CreateSession/index.js, v2/client/src/components/pages/Dashboard/Dashboard.style.js, v2/client/src/components/pages/Dashboard/index.js, v2/client/src/components/pages/LandingPage/LandingPage.style.js, v2/client/src/components/pages/LandingPage/index.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionActions.Style.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/components/pages/SignUp/index.js, v2/client/src/components/pages/UserResults/index.js, v2/server/controllers/users/trainer/signUp.js
relates to #453, #455, #456, #460, #461, #462, #463 , #464, #465, #466, #470, #458, #471
=> Enhancement

v2/client/src/components/pages/ViewSessions/ViewSessions.Style.js, v2/client/src/components/pages/ViewSessions/index.js
=> add upcoming sessions and sort sessions

v2/client/src/components/common/List/EmailsList.js, v2/client/src/components/pages/SessionDetails/ManageAttendees/EmailTemplate.js, v2/client/src/components/pages/SessionDetails/ManageAttendees/index.js
=> Empty email list

v2/client/src/actions/users.js, v2/client/src/components/pages/AddTrainer/index.js, v2/server/__test__/api/addTrainerToGroup.js, v2/server/controllers/users/addTrainerToGroup.js, v2/server/helpers/emails/emailNewTrainerLoginDetails.js, v2/server/helpers/emails/sendRegisteredTranierEmail.js
relates to #505 
- frontend changes:
when click on ok show loading to prevent user from double clicks.
- backend changes 
when locallead click add new trainer
if the trainer is alredy registered and added to the same local lead group that is someone trying to 
add  him into this local lead then show error msg "This trainer is already registered in 
<localLeadName> group".
send email for registered trainer if someone added him with no login details as new trainer
=> Fix Add trainer issues

v2/client/src/components/pages/Dashboard/index.js, v2/client/src/components/pages/MyProfile/index.js, v2/client/src/components/pages/SignUp/index.js, v2/server/controllers/login.js, v2/server/controllers/users/getUserInfo.js, v2/server/controllers/users/trainer/signUp.js, v2/server/database/data/development/users.js, v2/server/database/models/User.js
relates #509 , #510 , #508 
- To test it: 
rebuild DB
=> Add trainer manager

v2/client/src/actions/groupSessionsAction.js, v2/client/src/components/common/EditEmail/index.js, v2/client/src/components/common/Menu/Menu.style.js, v2/client/src/components/common/Menu/index.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/components/pages/SignUp/SignUp.style.js, v2/server/database/models/User.js
retate #526, #527, #530, #532, #531 
- changing defalut value for officialLocalLead to be false
To test it : 
rebiuld DB
=> Fixing Bugs + Enhancement

v2/client/src/components/common/BehavioralInsight/BehavioralInsight.style.js, v2/client/src/components/common/BehavioralInsight/Explanation.js, v2/client/src/components/common/BehavioralInsight/Participant.js, v2/client/src/components/common/BehavioralInsight/Survey.js, v2/client/src/components/common/BehavioralInsight/Trainer.js, v2/client/src/components/pages/ParticipantBehavioral/index.js, v2/client/src/components/pages/UserResults/index.js, v2/client/src/components/pages/ViewParticipant/index.js
=> add explanation paragraph to behavioral insight

v2/client/src/components/common/EditEmail/index.js
=> dynamically render titles for send email view

v2/client/src/components/common/AntdModal/index.js, v2/client/src/components/common/Feedback/index.js, v2/client/src/components/common/Reach/index.js, v2/client/src/components/pages/SessionDetails/InviteAndPromote/index.js, v2/client/src/components/pages/SessionDetails/ManageAttendees/index.js, v2/client/src/components/pages/SessionDetails/SessionDetails.Style.js, v2/client/src/components/pages/SessionDetails/SessionSurveys/index.js, v2/client/src/components/pages/SessionDetails/SessionTopDetails.js, v2/client/src/components/pages/SessionDetails/index.js, v2/client/src/components/pages/UserResults/UserResults.style.js, v2/client/src/components/pages/UserResults/index.js
=> Change find out more button to i icon

v2/client/src/components/pages/survey/Questions.style.js, v2/client/src/components/pages/survey/SurveyQs.js, v2/client/src/components/pages/survey/index.js, v2/server/__test__/database/queries/update3and6monthEmails.js, v2/server/__test__/helpers/get3and6MonthDates.js, v2/server/constants.js, v2/server/controllers/sessionDetails/confirmEmailRegistration.js, v2/server/controllers/sessionDetails/updateAttendeesList.js, v2/server/controllers/users/participantSurveyStatus.js, v2/server/database/DBConstants.js, v2/server/database/queries/addSession.js, v2/server/database/queries/sessionDetails/scheduleEmails.js, v2/server/database/queries/sessionDetails/session.js, v2/server/database/queries/surveys/index.js, v2/server/helpers/get3and6MonthDates.js
Relates to #590, #600, #599  and #537 
Regarding the #590 bug, here's what was causing the problem:
- We were looking for sessionType but in db its stored as type
- In our constants we have the session listed as a number but in the db we were storing as string
- We weren't checking to see if the survey was a pre survey in which case it didn't matter if the pre survey questions hadn't been filled in 
The only one I'm concerned about causing bugs elsewhere is changing the constants for sessionTypes 1, 2 and 3 to strings. Haven't come across any issues but let me know if this will be a problem!  
Regarding #599 - we currently don't have the video, so whoever approves and merges this, please create a new issue reminding us to add the video 
Regarding #537 - I was unsure whether this included …
=> Survey updates

v2/server/controllers/survey/storeSurvey.js, v2/server/database/queries/surveys/storeResponse.js
Save the participant field in the Response document
relates #606
=> Add participant id to the response document

v2/client/package-lock.json, v2/client/package.json, v2/client/src/components/common/NotSupported/index.js, v2/client/src/index.js
=> Add msg for IE users to inform them it is not supported

v2/client/src/components/pages/survey/SurveyQs.js, v2/client/src/components/pages/survey/index.js, v2/server/controllers/survey/storeSurvey.js
=> fix survey participants fields

v2/client/src/components/pages/AddTrainer/index.js, v2/client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, v2/client/src/helpers/createGroupedLocalLeads.js
=> Simon bugfixes s5

v2/client/src/actions/groupSessionsAction.js, v2/client/src/components/common/EditEmail/EditEmail.style.js, v2/client/src/components/common/EditEmail/index.js, v2/client/src/components/pages/survey/EnterPIN.js, v2/client/src/components/pages/survey/index.js, v2/server/controllers/users/participantSurveyStatus.js, v2/server/database/queries/surveys/index.js
=> Bug fixing

v2/client/src/actions/sessionAction.js, v2/client/src/components/common/EditEmail/index.js, v2/client/src/components/pages/CreateSession/index.js, v2/client/src/components/pages/SessionDetails/DrawerContent.js, v2/client/src/components/pages/SessionDetails/ManageAttendees/SendReminderEmails.js, v2/client/src/components/pages/SessionDetails/SessionSurveys/SendSurveyLink.js, v2/client/src/components/pages/SessionDetails/SessionSurveys/SurveyContent.js, v2/server/__test__/database/schema/user.js, v2/server/controllers/sessionDetails/confirmEmailRegistration.js, v2/server/controllers/sessionDetails/updateAttendeesList.js, v2/server/helpers/index.js
=> Fix bugs s5

client/src/actions/users.js, client/src/components/common/Reach/index.js, client/src/components/pages/UserResults/index.js, client/src/components/pages/UserResults/panels.js, client/src/components/pages/ViewSessions/index.js, client/src/components/pages/survey/EnterPIN.js, server/__test__/api/user.getUserResults.js, server/controllers/users/user.js, server/database/dbConnection.js, server/database/queries/behavioralInsight/filtereData.js, server/database/queries/feedback/filterFeedback.js, server/database/queries/users/filterSession.js, server/database/queries/users/filterSurveys.js, server/helpers/getResponseRate.js
=> Filter reach results

client/src/components/pages/ParticipantBehavioral/index.js, client/src/components/pages/SessionDetails/SessionDetails.Style.js, client/src/components/pages/SessionDetails/UserManual.js, server/database/data/development/questions.js, server/database/data/production/questions.js
- Updates Manage invitees/ attendees pages
- Removes BE questions from follow up surveys
=> Updates Manage Participant explanation and updates questions

client/src/components/pages/survey/index.js, client/src/constants/index.js, server/__test__/api/getSurveyQs.js, server/__test__/api/storeSurvey.js, server/__test__/database/queries/getResponseCount.js, server/__test__/database/queries/surveyQueries.js, server/__test__/database/schema/answer.js, server/__test__/database/schema/question.js, server/__test__/database/schema/response.js, server/constants.js, server/controllers/behavioralInsight/getFilteredBehavioral.js, server/controllers/feedback/getFeedback.js, server/controllers/survey/storeSurvey.js, server/database/data/development/answers.js, server/database/data/development/questions.js, server/database/data/development/responses.js, server/database/data/production/questions.js, server/database/data/test/answers.js, server/database/data/test/questions.js, server/database/data/test/responses.js, server/database/queries/behavioralInsight/filtereData.js, server/helpers/behavioralFormulae.js, server/helpers/formulaeParticipants.js, server/helpers/formulaeTrainers.js, server/helpers/participantBehavioral(legacy).js
- Change constants so pre-2-day and pre-session-1 are both the pre-course survey
- Change database questions to remove pre course survey questions rendering twice
- Hide session 1 from unnecessary questions in behavioural results
=> Pre results fix > #685

client/src/components/common/EditEmail/index.js, client/src/components/common/EmailTemplate/index.js, client/src/components/pages/SessionDetails/DrawerContent.js, client/src/components/pages/SessionDetails/SessionSurveys/ScheduleEmailsList.js, client/src/components/pages/SessionDetails/SessionSurveys/ScheduledEmailPreview.js, client/src/components/pages/SessionDetails/index.js
=> view scheduled emails

client/src/components/App.js, client/src/components/common/EditEmail/index.js, client/src/components/common/List/TrainerList.js, client/src/components/common/Navbar/index.js, client/src/components/pages/LandingPage/AboutUs.js, client/src/components/pages/LandingPage/index.js, client/src/components/pages/LocalLeadsAndManagersList/index.js, client/src/components/pages/Login/LoginParticipant.js, client/src/components/pages/ParticipantBehavioral/index.js, client/src/components/pages/SessionDetails/InviteAndPromote/InviteeList.js, client/src/components/pages/SessionDetails/PrintSessionDetails.js, client/src/components/pages/SessionDetails/PrintSessionDetails.style.js, client/src/components/pages/SessionDetails/PrintableComponent.js, client/src/components/pages/SessionDetails/SessionActions/SessionEdit.js, client/src/components/pages/SessionDetails/UserManual.js, client/src/components/pages/SessionDetails/index.js, client/src/components/pages/SessionsFiles/index.js, client/src/components/pages/SignUp/index.js, client/src/components/pages/survey/ConfirmSurvey.js, client/src/components/pages/survey/SurveyQs.js, server/helpers/emails/sendSurvey.js
fixes: #732, #729, #728, #726, #725
=> Simon bugfixes post sprints

client/src/components/pages/survey/SurveyQs.js, client/src/constants/index.js, server/database/data/development/questions.js, server/database/data/production/questions.js, server/database/data/test/questions.js, server/database/models/Participant.js, server/database/queries/users/getParticipantsDemogrphics.js
=> gender options

server/constants.js
=> fix reach results

client/package-lock.json, client/package.json, client/src/components/common/IEMessage/index.js, client/src/components/pages/LandingPage/AboutUs.js, client/src/components/pages/Login/Login.js, client/src/components/pages/ParticipantLogin/AccessSurveysTab.js, client/src/components/pages/SignUp/index.js
=>  show warning message on IE

client/src/components/common/Menu/index.js
=> remove admin sessions and results
